### ISSUE TITLE
Issue on Import btzen

### ISSUE THREAD

**Issue by jbsky** [wrobell/btzen#4]
Hello,

I'm starting from a fresh Debian installation and I give a try of https://github.com/wrobell/btzen/blob/master/scripts/btzen-connect, but import has a problem.

Traceback (most recent call last):
  File "./test1.py", line 26, in <module>
    import btzen
  File "/usr/local/lib/python3.7/dist-packages/btzen/__init__.py", line 20, in <module>
    from .btweight import WeightFlags, WeightData, WeightMeasurement
  File "/usr/local/lib/python3.7/dist-packages/btzen/btweight.py", line 29, in <module>
    from .device import InfoCharacteristic, DeviceCharacteristic, to_uuid
  File "/usr/local/lib/python3.7/dist-packages/btzen/device.py", line 36, in <module>
    from .bus import Bus
  File "/usr/local/lib/python3.7/dist-packages/btzen/bus.py", line 38, in <module>
    class Bus:
  File "/usr/local/lib/python3.7/dist-packages/btzen/bus.py", line 39, in Bus
    bus = contextvars.ContextVar[tp.Optional['Bus']]('bus', default=None)
TypeError: 'NoneType' object is not callable

I have a doubt about the following installation: pip3 install contextvars

Can you help me solve this problem?

Thanking you in advance,

Sincerely

Julien

**Comment by wrobell** [comment]
Unfortunately, I cannot test this with Python 3.7 anymore. Please use Python 3.8, which is the latest stable version of the language and was released over 18 months ago.

**Comment by jbsky** [comment]
Thanks for your reactivity, indeed, I saw that you need python3.8, the problem is that you have to compile it and that's what I'm doing.

So, I misread your description, sorry...

Julien

**Comment by wrobell** [comment]
Thanks for understanding.
